spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_2021?characterEncoding=utf8
    username: "root"
    possword: "123456"

  set myKey abc:
    host: 127.0.0.1

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.s.mapperpringbootdemo2021

server.port: 8080
server.servlet.context-path: /wzj

